source "https://api.berkshelf.com"


# 1.4.6+ of python is broken for chef 10.x
cookbook 'python', "~> 1.4.4"
cookbook 'sudo', "~> 2.5.2"
cookbook 'openssh', "~> 1.3.4"
cookbook 'openssl', "~> 1.1.0"
cookbook 'hostsfile'

metadata