#
# DO NOT EDIT THIS FILE DIRECTLY - UNLESS YOU KNOW WHAT YOU ARE DOING
#

user node.tablespoon-riemann.user do
  action :create
  supports :manage_home => true
  home "/home/#{node.tablespoon-riemann.user}"
  shell "/bin/bash"
  not_if "getent passwd #{node.tablespoon-riemann.user}"
end

group node.tablespoon-riemann.group do
  action :modify
  members ["#{node.tablespoon-riemann.user}"]
  append true
end


private_ip = my_private_ip()
public_ip = my_public_ip()



# Pre-Experiment Code



# Configuration Files

