# Start Bugfix: https://github.com/berkshelf/berkshelf-api/issues/112
Encoding.default_external = "UTF-8"
# End Bugfix

source 'https://supermarket.chef.io'
cookbook 'kagent', github: 'karamelchef/kagent-chef', branch: 'master'
metadata
