source "https://api.berkshelf.com"

metadata

cookbook 'java'
cookbook 'git', '<4.2.3'
cookbook 'hops', github: 'hopshadoop/hops-hadoop-chef'
cookbook 'ndb', github: 'hopshadoop/ndb-chef'
cookbook 'hadoop', github: 'hopshadoop/apache-hadoop-chef'
cookbook 'kagent', github: 'karamelchef/kagent-chef'