source "https://api.berkshelf.com"

metadata

cookbook 'kagent', github: 'karamelchef/kagent-chef', branch: "master"
cookbook 'ndb', github: "hopshadoop/ndb-chef", branch: "master"
cookbook 'collectd', github: "hopshadoop/collectd-chef", branch: "master"

cookbook 'python', "~> 1.4.4"
cookbook 'openssh', "~> 1.3.4"
cookbook 'openssl', "~> 1.1.0"
#cookbook 'glassfish', "~> 0.5.30"
cookbook 'glassfish', github: "realityforge/chef-glassfish", branch: "master" 